# Generated by Django 4.2.3 on 2023-07-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="姓名")),
                (
                    "sex",
                    models.CharField(
                        choices=[("1", "帅哥"), ("0", "美女")],
                        default="1",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.PositiveIntegerField(default=0, verbose_name="年龄")),
                (
                    "username",
                    models.CharField(max_length=64, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=256, verbose_name="密码")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
            ],
        ),
    ]
