# Generated by Django 4.2.3 on 2023-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=64, null=True, verbose_name="用户的邮箱"
            ),
        ),
    ]
