# Generated by Django 4.2.3 on 2023-07-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_email"),
    ]

    operations = [
        migrations.AlterModelTable(name="user", table="user",),
    ]
